### Register 
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "email": "test@example.com",
  "password": "password123"
}

### Register 2
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "testuser2",
  "email": "test2@example.com",
  "password": "password123"
}

### Register 3
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "testuser3",
  "email": "test3@example.com",
  "password": "password123"
}

### Login 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### Login 2
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "password123"
}

### Me
GET http://localhost:3000/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTNlMDM4Mzc5N2RkZjkwNTM3YzA5YTQiLCJpYXQiOjE3NjYzNjU5MTYsImV4cCI6MTc2NjM2NjgxNn0.rL2wTJ-s_3Q1vVzypUJDFpAW5Jv7jYyW-W43BBhsWTw


### FRIENDS
### Send Request
POST http://localhost:3000/friends/send-request
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTNiOGI1Y2ZlOWYyMzA0OGY0ZGJhMjEiLCJpYXQiOjE3NjYwMjU4NTIsImV4cCI6MTc2NjAyNjc1Mn0.9Vy2sywfnlPNBovehRs-esj68xr8BTGxGkOA9jK1aLo

{
  "userId": "693b8b5cfe9f23048f4dba21",
  "username": "testuser2",
  "discriminator": "4090"
}

### Get Requests
GET http://localhost:3000/friends/requests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTNiOGI1Y2ZlOWYyMzA0OGY0ZGJhMjEiLCJpYXQiOjE3NjYwMjU4NTIsImV4cCI6MTc2NjAyNjc1Mn0.9Vy2sywfnlPNBovehRs-esj68xr8BTGxGkOA9jK1aLo

### List friends
GET http://localhost:3000/friends/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTNlMDM4Mzc5N2RkZjkwNTM3YzA5YTQiLCJpYXQiOjE3NjYzNjU5MTYsImV4cCI6MTc2NjM2NjgxNn0.rL2wTJ-s_3Q1vVzypUJDFpAW5Jv7jYyW-W43BBhsWTw

### Respond to request
POST http://localhost:3000/friends/respond-to-request
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTNiOGI1Y2ZlOWYyMzA0OGY0ZGJhMjEiLCJpYXQiOjE3NjYwMjU4NTIsImV4cCI6MTc2NjAyNjc1Mn0.9Vy2sywfnlPNBovehRs-esj68xr8BTGxGkOA9jK1aLo

{
  "userId": "693b8b5cfe9f23048f4dba21",
  "status": true
}

### Logout
POST http://localhost:3000/auth/logout